

let verbs =[
     {
       "infinitive":"arise",
        "pastSimple":"arose",
        "pastParticiple":"arisen"
     },
     {
        "infinitive":"awake",
        "pastSimple":"awoke",
        "pastParticiple":"awoken"
     },
     {
        "infinitive":"bear",
        "pastSimple":"bore",
        "pastParticiple":"borne"
     },
     {
        "infinitive":"beat",
        "pastSimple":"beat",
        "pastParticiple":"beaten"
     },
     {
        "infinitive":"",
        "pastSimple":"arise",
        "pastParticiple":"arose"
     },
     {
        "infinitive":"become",
        "pastSimple":"became",
        "pastParticiple":"become"
     },
     {
        "infinitive":"begin",
        "pastSimple":"began",
        "pastParticiple":"begun"
     },
     {
        "infinitive":"bend",
        "pastSimple":"bent",
        "pastParticiple":"bent"
     },
     {
        "infinitive":"beset",
        "pastSimple":"beset",
        "pastParticiple":"beset"
     }
     ,
     {
        "infinitive":"bet",
        "pastSimple":"bet",
        "pastParticiple":"bet"
     }
     ,
     {
        "infinitive":"bid",
        "pastSimple":"bid",
        "pastParticiple":"bid"
     }
     ,
     {
        "infinitive":"bind",
        "pastSimple":"bound",
        "pastParticiple":"bound"
     }
     ,
     {
        "infinitive":"bite",
        "pastSimple":"bit",
        "pastParticiple":"bitten"
     }
     ,
     {
        "infinitive":"bleed",
        "pastSimple":"bled",
        "pastParticiple":"bled"
     }
     ,
     {
        "infinitive":"blow",
        "pastSimple":"blew",
        "pastParticiple":"blown"
     }
      ,
     {
        "infinitive":"break",
        "pastSimple":"broke",
        "pastParticiple":"broken"
     }
 ,
     {
        "infinitive":"breed",
        "pastSimple":"bred",
        "pastParticiple":"bred"
     }

 ,
     {
        "infinitive":"bring",
        "pastSimple":"brought",
        "pastParticiple":"brought"
     }
 ,
     {
        "infinitive":"broadcast",
        "pastSimple":"broadcast",
        "pastParticiple":"broadcast"
     },
     {
        "infinitive":"build",
        "pastSimple":"built",
        "pastParticiple":"built"
     },
     {
        "infinitive":"burn",
        "pastSimple":"burnt",
        "pastParticiple":"burnt"
     },
     {
        "infinitive":"burst",
        "pastSimple":"burst",
        "pastParticiple":"burst"
     },
     {
        "infinitive":"buy",
        "pastSimple":"bought",
        "pastParticiple":"bought"
     },
     {
        "infinitive":"cast",
        "pastSimple":"cast",
        "pastParticiple":"cast"
     },
     {
        "infinitive":"catch",
        "pastSimple":"caught",
        "pastParticiple":"caught"
     },
     {
        "infinitive":"choose",
        "pastSimple":"chose",
        "pastParticiple":"chosen"
     },
     {
        "infinitive":"cling",
        "pastSimple":"clung",
        "pastParticiple":"clung"
     },
     {
        "infinitive":"come",
        "pastSimple":"came",
        "pastParticiple":"come"
     },
     {
        "infinitive":"cost",
        "pastSimple":"cost",
        "pastParticiple":"cost"
     },
     {
        "infinitive":"creep",
        "pastSimple":"crept",
        "pastParticiple":"crept"
     },
     {
        "infinitive":"cut",
        "pastSimple":"cut",
        "pastParticiple":"cut"
     },
     {
        "infinitive":"deal",
        "pastSimple":"dealt",
        "pastParticiple":"dealt"
     },
     {
        "infinitive":"dig",
        "pastSimple":"dug",
        "pastParticiple":"dug"
     },
     {
        "infinitive":"dive",
        "pastSimple":"dived",
        "pastParticiple":"dived"
     },
     {
        "infinitive":"do",
        "pastSimple":"did",
        "pastParticiple":"done"
     },
     {
        "infinitive":"draw",
        "pastSimple":"drew",
        "pastParticiple":"drawn"
     },
     {
        "infinitive":"dream",
        "pastSimple":"dreamed",
        "pastParticiple":"dreamed"
     },
     {
        "infinitive":"drink",
        "pastSimple":"drank",
        "pastParticiple":"drunk"
     },
     {
        "infinitive":"drive",
        "pastSimple":"drove",
        "pastParticiple":"driven"
     },
     {
        "infinitive":"eat",
        "pastSimple":"ate",
        "pastParticiple":"eaten"
     },
     {
        "infinitive":"fall",
        "pastSimple":"fell",
        "pastParticiple":"fallen"
     },
     {
        "infinitive":"",
        "pastSimple":"",
        "pastParticiple":""
     }






];
$.getJSON( "data.json", function( data ) {
  var items = [];
  $.each( data, function( data) {
    items.push( data);
  });
});
console.log(items[0].infinitive);


